
#ifndef SDKCONFIG_H_INCLUDED
#define SDKCONFIG_H_INCLUDED
// Automatically generated file. Do not edit.

    #define CONFIG_LV_CONF_SKIP 1
#define CONFIG_LV_COLOR_DEPTH_16 1
#define CONFIG_LV_COLOR_DEPTH 16
#define CONFIG_LV_COLOR_16_SWAP 1
#define CONFIG_LV_COLOR_MIX_ROUND_OFS 128
#define CONFIG_LV_MEM_SIZE_KILOBYTES 32
#define CONFIG_LV_MEM_BUF_MAX_NUM 16
#define CONFIG_LV_DISP_DEF_REFR_PERIOD 30
#define CONFIG_LV_INDEV_DEF_READ_PERIOD 30
#define CONFIG_LV_DPI_DEF 130
#define CONFIG_LV_DRAW_COMPLEX 1
#define CONFIG_LV_SHADOW_CACHE_SIZE 0
#define CONFIG_LV_CIRCLE_CACHE_SIZE 4
#define CONFIG_LV_IMG_CACHE_DEF_SIZE 0
#define CONFIG_LV_GRADIENT_MAX_STOPS 2
#define CONFIG_LV_GRAD_CACHE_DEF_SIZE 0
#define CONFIG_LV_DISP_ROT_MAX_BUF 10240
#define CONFIG_LV_LOG_LEVEL 
#define CONFIG_LV_USE_ASSERT_NULL 1
#define CONFIG_LV_USE_ASSERT_MALLOC 1
#define CONFIG_LV_ASSERT_HANDLER_INCLUDE "assert.h"
#define CONFIG_LV_USE_USER_DATA 1
#define CONFIG_LV_ATTRIBUTE_MEM_ALIGN_SIZE 1
#define CONFIG_LV_FONT_MONTSERRAT_16 1
#define CONFIG_LV_FONT_MONTSERRAT_24 1
#define CONFIG_LV_FONT_MONTSERRAT_32 1
#define CONFIG_LV_FONT_MONTSERRAT_48 1
#define CONFIG_LV_FONT_DEFAULT_MONTSERRAT_16 1
#define CONFIG_LV_TXT_ENC_UTF8 1
#define CONFIG_LV_TXT_BREAK_CHARS " ,.;:-_"
#define CONFIG_LV_TXT_LINE_BREAK_LONG_LEN 0
#define CONFIG_LV_TXT_LINE_BREAK_LONG_PRE_MIN_LEN 
#define CONFIG_LV_TXT_LINE_BREAK_LONG_POST_MIN_LEN 
#define CONFIG_LV_TXT_COLOR_CMD "#"
#define CONFIG_LV_USE_ARC 1
#define CONFIG_LV_USE_BAR 1
#define CONFIG_LV_USE_BTN 1
#define CONFIG_LV_USE_BTNMATRIX 1
#define CONFIG_LV_USE_CANVAS 1
#define CONFIG_LV_USE_CHECKBOX 1
#define CONFIG_LV_USE_DROPDOWN 1
#define CONFIG_LV_USE_LABEL 1
#define CONFIG_LV_USE_IMG 1
#define CONFIG_LV_LABEL_TEXT_SELECTION 1
#define CONFIG_LV_LABEL_LONG_TXT_HINT 1
#define CONFIG_LV_USE_LINE 1
#define CONFIG_LV_USE_ROLLER 1
#define CONFIG_LV_ROLLER_INF_PAGES 7
#define CONFIG_LV_USE_SLIDER 1
#define CONFIG_LV_USE_SWITCH 1
#define CONFIG_LV_USE_TEXTAREA 1
#define CONFIG_LV_TEXTAREA_DEF_PWD_SHOW_TIME 1500
#define CONFIG_LV_USE_TABLE 1
#define CONFIG_LV_USE_ANIMIMG 1
#define CONFIG_LV_USE_CALENDAR 1
#define CONFIG_LV_USE_CALENDAR_HEADER_ARROW 1
#define CONFIG_LV_USE_CALENDAR_HEADER_DROPDOWN 1
#define CONFIG_LV_USE_CHART 1
#define CONFIG_LV_USE_COLORWHEEL 1
#define CONFIG_LV_USE_IMGBTN 1
#define CONFIG_LV_USE_KEYBOARD 1
#define CONFIG_LV_USE_LED 1
#define CONFIG_LV_USE_LIST 1
#define CONFIG_LV_USE_MENU 1
#define CONFIG_LV_USE_METER 1
#define CONFIG_LV_USE_MSGBOX 1
#define CONFIG_LV_USE_SPINBOX 1
#define CONFIG_LV_USE_SPINNER 1
#define CONFIG_LV_USE_TABVIEW 1
#define CONFIG_LV_USE_TILEVIEW 1
#define CONFIG_LV_USE_WIN 1
#define CONFIG_LV_USE_SPAN 1
#define CONFIG_LV_SPAN_SNIPPET_STACK_SIZE 64
#define CONFIG_LV_USE_THEME_DEFAULT 1
#define CONFIG_LV_THEME_DEFAULT_GROW 1
#define CONFIG_LV_THEME_DEFAULT_TRANSITION_TIME 80
#define CONFIG_LV_USE_THEME_BASIC 1
#define CONFIG_LV_USE_FLEX 1
#define CONFIG_LV_USE_GRID 1
#define CONFIG_LV_FS_POSIX_LETTER 
#define CONFIG_LV_FS_POSIX_CACHE_SIZE 
#define CONFIG_LV_FS_WIN32_LETTER 
#define CONFIG_LV_FS_WIN32_CACHE_SIZE 
#define CONFIG_LV_FS_FATFS_LETTER 
#define CONFIG_LV_FS_FATFS_CACHE_SIZE 
#define CONFIG_LV_FREETYPE_CACHE_SIZE 
#define CONFIG_LV_FREETYPE_CACHE_FT_FACES 
#define CONFIG_LV_FREETYPE_CACHE_FT_SIZES 
#define CONFIG_LV_USE_SNAPSHOT 1
#define CONFIG_LV_BUILD_EXAMPLES 1
#define CONFIG_GEL_COLLECTIONS 1
#define CONFIG_GEL_PAGE_MANAGER 1
#define CONFIG_GEL_PAGEMANAGER_CONFIGURATION_HEADER "gel_pman_conf.h"
#define CONFIG_GEL_CONF_INCLUDE_PATH "main/config main components/lvgl"
#define CONFIG_LV_TFT_DISPLAY_PROTOCOL_SPI 1
#define CONFIG_LV_PREDEFINED_DISPLAY_WT32_SC01 1
#define CONFIG_LV_TFT_DISPLAY_CONTROLLER_ST7796S 1
#define CONFIG_LV_DISPLAY_ORIENTATION_LANDSCAPE 1
#define CONFIG_LV_DISPLAY_ORIENTATION 2
#define CONFIG_LV_TFT_DISPLAY_X_OFFSET 
#define CONFIG_LV_TFT_DISPLAY_Y_OFFSET 
#define CONFIG_CUSTOM_DISPLAY_BUFFER_BYTES 
#define CONFIG_LV_TFT_DISPLAY_SPI2_HOST 1
#define CONFIG_LV_TFT_DISPLAY_SPI_TRANS_MODE_SIO 1
#define CONFIG_LV_TFT_DISPLAY_SPI_HALF_DUPLEX 1
#define CONFIG_LV_TFT_CUSTOM_SPI_CLK_DIVIDER 2
#define CONFIG_LV_DISP_RA8875_PLLDIVM 
#define CONFIG_LV_DISP_RA8875_PLLDIVN 
#define CONFIG_LV_DISP_RA8875_PLLDIVK 
#define CONFIG_LV_DISP_RA8875_PCLK_MULTIPLIER 
#define CONFIG_LV_DISP_RA8875_HORI_NON_DISP_PERIOD 
#define CONFIG_LV_DISP_RA8875_HSYNC_START 
#define CONFIG_LV_DISP_RA8875_HSYNC_PW 
#define CONFIG_LV_DISP_RA8875_VERT_NON_DISP_PERIOD 
#define CONFIG_LV_DISP_RA8875_VSYNC_START 
#define CONFIG_LV_DISP_RA8875_VSYNC_PW 
#define CONFIG_LV_DISP_SPI_MOSI 13
#define CONFIG_LV_DISP_SPI_MISO 
#define CONFIG_LV_DISP_SPI_INPUT_DELAY_NS 
#define CONFIG_LV_DISP_SPI_IO2 
#define CONFIG_LV_DISP_SPI_IO3 
#define CONFIG_LV_DISP_SPI_CLK 14
#define CONFIG_LV_DISPLAY_USE_SPI_CS 1
#define CONFIG_LV_DISP_SPI_CS 15
#define CONFIG_LV_DISPLAY_USE_DC 1
#define CONFIG_LV_DISP_PIN_DC 21
#define CONFIG_LV_DISP_USE_RST 1
#define CONFIG_LV_DISP_PIN_RST 22
#define CONFIG_LV_DISP_PIN_BUSY 
#define CONFIG_LV_DISP_BACKLIGHT_PWM 1
#define CONFIG_LV_BACKLIGHT_ACTIVE_LVL 1
#define CONFIG_LV_DISP_PIN_BCKL 23
#define CONFIG_LV_I2C 1
#define CONFIG_LV_I2C_DISPLAY_PORT 0
#define CONFIG_LV_TOUCH_CONTROLLER 2
#define CONFIG_LV_TOUCH_CONTROLLER_FT6X06 1
#define CONFIG_LV_I2C_TOUCH 1
#define CONFIG_LV_TOUCH_SPI_MISO 
#define CONFIG_LV_TOUCH_SPI_MOSI 
#define CONFIG_LV_TOUCH_SPI_CLK 
#define CONFIG_LV_TOUCH_SPI_CS 
#define CONFIG_LV_TOUCH_PIN_IRQ 
#define CONFIG_LV_TOUCH_X_MIN 
#define CONFIG_LV_TOUCH_Y_MIN 
#define CONFIG_LV_TOUCH_X_MAX 
#define CONFIG_LV_TOUCH_Y_MAX 
#define CONFIG_LV_FT6X36_SWAPXY 1
#define CONFIG_LV_FT6X36_INVERT_Y 1
#define CONFIG_LV_TOUCHSCREEN_RESISTIVE_PIN_YU 
#define CONFIG_LV_TOUCHSCREEN_RESISTIVE_PIN_YD 
#define CONFIG_LV_TOUCHSCREEN_RESISTIVE_PIN_XL 
#define CONFIG_LV_TOUCHSCREEN_RESISTIVE_PIN_XR 
#define CONFIG_LV_TOUCH_RA8875_SAMPLE_TIME 
#define CONFIG_LV_TOUCH_RA8875_ADC_CLOCK 
#define CONFIG_LV_I2C_TOUCH_PORT_0 1
#define CONFIG_LV_I2C_TOUCH_PORT 0
#define CONFIG_I2C_MANAGER_0_ENABLED 1
#define CONFIG_I2C_MANAGER_0_SDA 18
#define CONFIG_I2C_MANAGER_0_SCL 19
#define CONFIG_I2C_MANAGER_0_FREQ_HZ 400000
#define CONFIG_I2C_MANAGER_0_TIMEOUT 20
#define CONFIG_I2C_MANAGER_0_LOCK_TIMEOUT 50
#define CONFIG_I2C_MANAGER_1_SDA 
#define CONFIG_I2C_MANAGER_1_SCL 
#define CONFIG_I2C_MANAGER_1_FREQ_HZ 
#define CONFIG_I2C_MANAGER_1_TIMEOUT 
#define CONFIG_I2C_MANAGER_1_LOCK_TIMEOUT 
#define CONFIG_I2C_MANAGER_0_ENABLED 1
#define CONFIG_I2C_MANAGER_0_SDA 18
#define CONFIG_I2C_MANAGER_0_SCL 19
#define CONFIG_I2C_MANAGER_0_FREQ_HZ 400000
#define CONFIG_I2C_MANAGER_0_TIMEOUT 20
#define CONFIG_I2C_MANAGER_0_LOCK_TIMEOUT 50
#define CONFIG_I2C_MANAGER_1_SDA 
#define CONFIG_I2C_MANAGER_1_SCL 
#define CONFIG_I2C_MANAGER_1_FREQ_HZ 
#define CONFIG_I2C_MANAGER_1_TIMEOUT 
#define CONFIG_I2C_MANAGER_1_LOCK_TIMEOUT 
#define CONFIG_LV_TOUCH_CONTROLLER 2
#define CONFIG_LV_TOUCH_CONTROLLER_FT6X06 1
#define CONFIG_LV_I2C_TOUCH 1
#define CONFIG_LV_TOUCH_SPI_MISO 
#define CONFIG_LV_TOUCH_SPI_MOSI 
#define CONFIG_LV_TOUCH_SPI_CLK 
#define CONFIG_LV_TOUCH_SPI_CS 
#define CONFIG_LV_TOUCH_PIN_IRQ 
#define CONFIG_LV_TOUCH_X_MIN 
#define CONFIG_LV_TOUCH_Y_MIN 
#define CONFIG_LV_TOUCH_X_MAX 
#define CONFIG_LV_TOUCH_Y_MAX 
#define CONFIG_LV_FT6X36_SWAPXY 1
#define CONFIG_LV_FT6X36_INVERT_Y 1
#define CONFIG_LV_TOUCHSCREEN_RESISTIVE_PIN_YU 
#define CONFIG_LV_TOUCHSCREEN_RESISTIVE_PIN_YD 
#define CONFIG_LV_TOUCHSCREEN_RESISTIVE_PIN_XL 
#define CONFIG_LV_TOUCHSCREEN_RESISTIVE_PIN_XR 
#define CONFIG_LV_TOUCH_RA8875_SAMPLE_TIME 
#define CONFIG_LV_TOUCH_RA8875_ADC_CLOCK 
#define CONFIG_LV_I2C_TOUCH_PORT_0 1
#define CONFIG_LV_I2C 1
#define CONFIG_LV_I2C_TOUCH_PORT 0
#define CONFIG_LV_TFT_DISPLAY_PROTOCOL_SPI 1
#define CONFIG_LV_PREDEFINED_DISPLAY_WT32_SC01 1
#define CONFIG_LV_TFT_DISPLAY_CONTROLLER_ST7796S 1
#define CONFIG_LV_DISPLAY_ORIENTATION_LANDSCAPE 1
#define CONFIG_LV_DISPLAY_ORIENTATION 2
#define CONFIG_LV_TFT_DISPLAY_X_OFFSET 
#define CONFIG_LV_TFT_DISPLAY_Y_OFFSET 
#define CONFIG_CUSTOM_DISPLAY_BUFFER_BYTES 
#define CONFIG_LV_TFT_DISPLAY_SPI2_HOST 1
#define CONFIG_LV_TFT_DISPLAY_SPI_TRANS_MODE_SIO 1
#define CONFIG_LV_TFT_DISPLAY_SPI_HALF_DUPLEX 1
#define CONFIG_LV_TFT_CUSTOM_SPI_CLK_DIVIDER 2
#define CONFIG_LV_DISP_RA8875_PLLDIVM 
#define CONFIG_LV_DISP_RA8875_PLLDIVN 
#define CONFIG_LV_DISP_RA8875_PLLDIVK 
#define CONFIG_LV_DISP_RA8875_PCLK_MULTIPLIER 
#define CONFIG_LV_DISP_RA8875_HORI_NON_DISP_PERIOD 
#define CONFIG_LV_DISP_RA8875_HSYNC_START 
#define CONFIG_LV_DISP_RA8875_HSYNC_PW 
#define CONFIG_LV_DISP_RA8875_VERT_NON_DISP_PERIOD 
#define CONFIG_LV_DISP_RA8875_VSYNC_START 
#define CONFIG_LV_DISP_RA8875_VSYNC_PW 
#define CONFIG_LV_DISP_SPI_MOSI 13
#define CONFIG_LV_DISP_SPI_MISO 
#define CONFIG_LV_DISP_SPI_INPUT_DELAY_NS 
#define CONFIG_LV_DISP_SPI_IO2 
#define CONFIG_LV_DISP_SPI_IO3 
#define CONFIG_LV_DISP_SPI_CLK 14
#define CONFIG_LV_DISPLAY_USE_SPI_CS 1
#define CONFIG_LV_DISP_SPI_CS 15
#define CONFIG_LV_DISPLAY_USE_DC 1
#define CONFIG_LV_DISP_PIN_DC 21
#define CONFIG_LV_DISP_USE_RST 1
#define CONFIG_LV_DISP_PIN_RST 22
#define CONFIG_LV_DISP_PIN_BUSY 
#define CONFIG_LV_DISP_BACKLIGHT_PWM 1
#define CONFIG_LV_BACKLIGHT_ACTIVE_LVL 1
#define CONFIG_LV_DISP_PIN_BCKL 23
#define CONFIG_LV_I2C_DISPLAY_PORT 0
#endif